### ISSUE TITLE
Updated OpenAI and ⚠ Unrecognized key(s) in object: 'API_URL'

### ISSUE THREAD

**Issue by IkeMane** [ltphen/sameday-tutorial#1]
There seems to be an issue with the API_URL within the next.config.js I tried to point it to my local server, http://localhost:5000/, and still got this error. I also tried to change the .env to http://localhost:5000/, but It's still not working.

Also, OpenAI changed how you create with their models. I tried to update this, but right now, how it is structured is not reorganizing the chunk.choices[0].delta.content

**Comment by atilla-the-hun** [comment]
Got the same problem. Anyone with a solution to this?

**Comment by ltphen** [comment]
Hello everyone. 
I'm sorry for not getting back to you sooner. It is because the URL is hardcoded here : 

https://github.com/ltphen/sameday-tutorial/blob/ed9706b59465db88166a58e7253dbbe59cc2b7eb/sameday-ui/app/page.tsx#L65

I will update the code to reflect that change and use the nextjs config. 

Concerning the Openai API, I will check as well. I will notify you when I push a change.

Thanks

**Comment by kishoreganth** [comment]
Any update on the issue. Please let us know

**Comment by ltphen** [comment]
Hello, everyone. It is solved on the last commit!
